"""
ml/evaluate_anomaly.py — Stage 7 anomaly-scenario classifier evaluation.

Recomputes the EXACT stratified 70/15/15 split used by ml/train_anomaly.py
(same seed 2077, same order of carve), scores the held-out test split with the
saved models/anomaly_classifier.joblib, and writes the Stage 7 MODEL CARD to
reports/stage7_anomaly_model.md.

The model card reports REAL numbers only — per-class precision/recall/F1,
macro/weighted F1, accuracy, confusion matrix (markdown), ROC-AUC (ovr,
weighted) and one-vs-rest average precision where computable — plus dataset
methodology, feature list, model metadata, and an explicit LIMITATIONS
section (synthetic data, label-generation bias, false_complaint is designed
to be near-indistinguishable from normal_success, metrics are NOT production
fraud-detection performance).

Usage (from the project root):
    python -m ml.evaluate_anomaly
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import sys

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_recall_fscore_support,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from ml.predict_anomaly import FEATURE_COLUMNS  # type: ignore
    from ml.train_anomaly import (  # type: ignore
        CATEGORICAL_FEATURES, RANDOM_STATE, SCENARIO_CLASSES, build_anomaly_pipeline,
    )
else:
    from ml.predict_anomaly import FEATURE_COLUMNS
    from ml.train_anomaly import (
        CATEGORICAL_FEATURES, RANDOM_STATE, SCENARIO_CLASSES, build_anomaly_pipeline,
    )

REPORT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "reports", "stage7_anomaly_model.md",
)

DATASET_NOTE = """
## Dataset

Synthetic anomaly-scenario dataset (Stage 7), generated by
`scripts/generate_anomaly_dataset.py` (seed 2077). Each row is one payment
transaction described by the 18 pinned features and labeled with the payment
SCENARIO that produced its evidence ({n_classes} classes).

The generator draws every scenario from a shared "healthy transaction" base
distribution and then overrides specific features per scenario — this is what
creates REALISTIC OVERLAP. Deliberate overlap/noise channels:

* generous multiplicative + additive jitter on all numerics (no clean
  decision boundaries);
* ~8% of `normal_success` rows get high gateway latency;
* ~6% of `normal_success` rows get `retry_count >= 3`;
* ~3% of `normal_success` rows show `debit_confirmation_count = 2` (a legit
  retry that resembles a double deduction), while ~30% of `double_deduction`
  rows show only one debit confirmation (invisible in the event stream);
* `incomplete_event_chain` rows overlap sparse-event rows of other classes;
* `suspicious_high_retry` overlaps the normal high-retry noise;
* `duplicate_transaction` rows have elevated `duplicate_event_count` plus
  roughly doubled gateway latency, with generous jitter;
* `false_complaint` rows look EXACTLY like `normal_success` in feature space —
  the evidence says success; the model is expected to fail on this class.

Because labels and features come from the SAME generator, the labels encode
the generator's assumptions (label-generation bias) — see Limitations.
"""


def _md_confusion_matrix(cm: np.ndarray, labels: list[str]) -> str:
    head = "| actual \\ predicted | " + " | ".join(labels) + " |"
    sep = "|" + "---|" * (len(labels) + 1)
    lines = [head, sep]
    for label, row in zip(labels, cm):
        lines.append(f"| **{label}** | " + " | ".join(str(int(v)) for v in row) + " |")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Stage 7 — evaluate anomaly-scenario classifier")
    ap.add_argument("--data", default="data/anomaly_transactions.csv")
    ap.add_argument("--models-dir", default="models")
    ap.add_argument("--report", default=REPORT_PATH)
    args = ap.parse_args()

    print("=" * 72)
    print("STAGE 7 — ANOMALY-SCENARIO CLASSIFIER EVALUATION")
    print("=" * 72)

    classifier_path = os.path.join(args.models_dir, "anomaly_classifier.joblib")
    meta_path = os.path.join(args.models_dir, "anomaly_preprocessors.joblib")
    if not (os.path.exists(classifier_path) and os.path.exists(meta_path)):
        raise FileNotFoundError(
            "anomaly artifacts missing — train first with: python -m ml.train_anomaly"
        )
    pipe = joblib.load(classifier_path)
    meta = joblib.load(meta_path)

    df = pd.read_csv(args.data)
    X = df[FEATURE_COLUMNS].copy()
    # Same integer encoding as ml/train_anomaly.py (codes == SCENARIO_CLASSES order)
    y = np.asarray(pd.Categorical(df["scenario"].astype(str), categories=SCENARIO_CLASSES).codes)

    # Identical split to ml/train_anomaly.py (same seed, same carve order)
    idx_tr, idx_te = train_test_split(
        np.arange(len(df)), test_size=0.15, random_state=RANDOM_STATE, stratify=y
    )
    idx_tr, idx_val = train_test_split(
        idx_tr, test_size=0.15 / 0.70, random_state=RANDOM_STATE, stratify=y[idx_tr]
    )

    X_te, y_te = X.iloc[idx_te], y[idx_te]
    y_pred = pipe.predict(X_te)
    y_proba = pipe.predict_proba(X_te)

    # Class order in proba columns -> scenario names (training used the
    # SCENARIO_CLASSES order, stored in the meta artifact)
    classes_meta = meta.get("scenario_classes") or SCENARIO_CLASSES
    class_names = [str(classes_meta[int(c)]) for c in pipe.named_steps["model"].classes_]
    # decode int codes back to scenario names for all string-based metrics
    _names = np.asarray(class_names)
    y_te = _names[y_te]
    y_pred = _names[y_pred]

    print(f"dataset : {args.data}  (test split: {len(idx_te):,} rows)")

    precision, recall, f1, support = precision_recall_fscore_support(
        y_te, y_pred, labels=class_names, zero_division=0
    )
    f1_macro = float(f1_score(y_te, y_pred, average="macro", zero_division=0))
    f1_weighted = float(f1_score(y_te, y_pred, average="weighted", zero_division=0))
    accuracy = float(accuracy_score(y_te, y_pred))
    cm = confusion_matrix(y_te, y_pred, labels=class_names)

    roc_auc = None
    try:
        # roc_auc_score sorts y_true's classes alphabetically; proba columns are
        # in training class order — reorder columns to match.
        alpha_order = np.argsort(np.asarray(class_names))
        roc_auc = float(roc_auc_score(
            y_te, y_proba[:, alpha_order], multi_class="ovr", average="weighted"
        ))
    except ValueError:
        pass  # a class missing from the test split makes OvR AUC undefined

    # Per-class average precision (undefined for a class with no positive rows)
    ap_per_class: dict[str, float | None] = {}
    for i, name in enumerate(class_names):
        y_bin = (y_te == name).astype(int)
        if y_bin.sum() == 0:
            ap_per_class[name] = None
        else:
            ap_per_class[name] = float(average_precision_score(y_bin, y_proba[:, i]))

    fc_idx = class_names.index("false_complaint")
    fc_recall = float(recall[fc_idx])
    fc_precision = float(precision[fc_idx])

    print(f"  accuracy          : {accuracy:.4f}")
    print(f"  f1 macro          : {f1_macro:.4f}")
    print(f"  f1 weighted       : {f1_weighted:.4f}")
    print(f"  roc-auc ovr (wtd) : {roc_auc:.4f}" if roc_auc is not None else
          "  roc-auc ovr (wtd) : n/a")
    print(f"  false_complaint R : {fc_recall:.4f}")

    # ---- model card --------------------------------------------------------
    counts = df["scenario"].astype(str).value_counts()
    dist_rows = "\n".join(
        f"| {s} | {int(counts.get(s, 0)):,} | {counts.get(s, 0) / len(df):6.2%} |"
        for s in SCENARIO_CLASSES
    )
    per_class_rows = "\n".join(
        f"| {name} | {precision[i]:.4f} | {recall[i]:.4f} | {f1[i]:.4f} | "
        f"{int(support[i]):,} | "
        + (f"{ap_per_class[name]:.4f}" if ap_per_class[name] is not None else "n/a")
        + " |"
        for i, name in enumerate(class_names)
    )
    report_text = f"""# Stage 7 Model Card — Anomaly-Scenario Classifier

Generated: {dt.datetime.now().isoformat(timespec="seconds")}
Model version: **{meta.get('model_version', 'synthetic-v1')}**

A dedicated multi-class classifier that predicts which payment SCENARIO
produced a transaction's evidence. The hybrid risk engine consumes
`P(not normal_success)` from `ml/predict_anomaly.py` as a SUPPORTING signal
only — never as the sole decision input.
{DATASET_NOTE.format(n_classes=len(SCENARIO_CLASSES))}
### Distribution ({len(df):,} rows)

| scenario | rows | share |
|---|---:|---:|
{dist_rows}

### Feature list (18 pinned columns, exact order)

{", ".join(f"`{c}`" for c in FEATURE_COLUMNS)}

Leakage rules hold: no `safe_to_release`, no `risk_score`/`recovery_risk`,
no recovery-decision fields, no anomaly label — only facts observable at
assessment time (asserted in `tests/test_anomaly_ml.py::test_no_target_leakage`).

## Model

* Algorithm: XGBoost (`XGBClassifier`, multi:softprob, 300 trees,
  max_depth 4, learning_rate 0.1, subsample 0.9, colsample_bytree 0.9,
  tree_method hist) inside a sklearn `Pipeline` with median-imputed numerics
  and constant-imputed + one-hot-encoded categoricals
  ({", ".join(CATEGORICAL_FEATURES)}; `handle_unknown="ignore"`).
* Seed: {RANDOM_STATE} (data split AND model).
* Split: stratified 70/15/15 (train/val/test). Headline numbers below are
  the held-out TEST split only.
* Artifact: `models/anomaly_classifier.joblib` (full fitted pipeline) +
  `models/anomaly_preprocessors.joblib` (meta: features, class order,
  version `{meta.get('model_version', 'synthetic-v1')}`, training metrics).

## Evaluation (held-out test split, {len(idx_te):,} rows)

| metric | value |
|---|---:|
| accuracy | {accuracy:.4f} |
| F1 (macro) | {f1_macro:.4f} |
| F1 (weighted) | {f1_weighted:.4f} |
| ROC-AUC (ovr, weighted) | {f"{roc_auc:.4f}" if roc_auc is not None else "n/a"} |

### Per-class results

| scenario | precision | recall | F1 | support | avg precision (OvR) |
|---|---:|---:|---:|---:|---:|
{per_class_rows}

### Confusion matrix (counts, rows = actual)

{_md_confusion_matrix(cm, class_names)}

**false_complaint** recall is {fc_recall:.4f} (precision {fc_precision:.4f}):
this is EXPECTED and honest. By design those rows are feature-identical to
`normal_success` — the payment evidence looks like a successful payment — so
a model that reads only payment evidence cannot separate them. The engine
must handle false complaints through other channels (claims, user history),
not this classifier.

## Limitations

* **Synthetic data only.** All rows come from a scripted generator; nothing
  here has been validated against real payment traffic.
* **No real banking fraud labels.** "Scenarios" are generator constructs, not
  audited real-world outcomes.
* **Label-generation bias.** Labels and features come from the SAME
  generator, so the label boundary is partially encoded in the features by
  construction; real data will not be so convenient.
* **Distribution shift risk.** Production traffic (latencies, retry policies,
  event vocabularies) will differ from the generator's assumptions, likely
  degrading these numbers.
* **These metrics are NOT production fraud-detection performance.** They
  characterize the synthetic benchmark only.
* **false_complaint is intentionally near-indistinguishable from
  `normal_success`.** Its low recall is expected and honest, not a bug.
"""
    os.makedirs(os.path.dirname(os.path.abspath(args.report)), exist_ok=True)
    with open(args.report, "w", encoding="utf-8") as f:
        f.write(report_text)
    print(f"\nModel card saved: {args.report}")


if __name__ == "__main__":
    main()
