"""initial schema: transactions, digital twin events, recovery decisions

Revision ID: f67049448be8
Revises: 
Create Date: 2026-10-02 02:23:47.238208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67049448be8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gateway_latency_ms', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('network_quality', sa.String(length=20), nullable=False),
    sa.Column('previous_failures', sa.Integer(), nullable=False),
    sa.Column('account_age_days', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=50), nullable=True),
    sa.Column('current_state', sa.String(length=32), nullable=False),
    sa.Column('failure_prediction', sa.String(length=50), nullable=True),
    sa.Column('failure_probability', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('safe_to_release_probability', sa.Float(), nullable=True),
    sa.Column('safe_to_release', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_current_state'), ['current_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('digital_twin_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('previous_state', sa.String(length=32), nullable=True),
    sa.Column('new_state', sa.String(length=32), nullable=False),
    sa.Column('failure_prediction', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('safe_to_release_probability', sa.Float(), nullable=True),
    sa.Column('safe_to_release', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digital_twin_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digital_twin_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_digital_twin_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_digital_twin_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_digital_twin_events_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('recovery_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('safe_to_release', sa.Boolean(), nullable=False),
    sa.Column('safe_to_release_probability', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=32), nullable=False),
    sa.Column('policy_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_decisions_transaction_id'), ['transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_decisions_transaction_id'))

    op.drop_table('recovery_decisions')
    with op.batch_alter_table('digital_twin_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digital_twin_events_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_digital_twin_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_digital_twin_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_digital_twin_events_event_id'))

    op.drop_table('digital_twin_events')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_transactions_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_current_state'))

    op.drop_table('transactions')
    # ### end Alembic commands ###
